name: Test & Deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip install tensorboard
          pip install -I protobuf==3.20.1
      - run: npm ci
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          TEST_GITHUB_REPO: https://github.com/iterative/cml_qa_tests_dummy
          TEST_GITHUB_SHA: 0cd16da26e35f8e5d57b2549a97e22618abf08f6
          TEST_GITLAB_TOKEN: ${{ secrets.TEST_GITLAB_TOKEN }}
          TEST_GITLAB_REPO: https://gitlab.com/iterative.ai/cml_qa_tests_dummy
          TEST_GITLAB_SHA: f8b8b49a253243830ef59a7f090eb887157b2b67
          TEST_BBCLOUD_TOKEN: ${{ secrets.TEST_BBCLOUD_TOKEN }}
          TEST_BBCLOUD_REPO: https://bitbucket.org/iterative-ai/cml-qa-tests-dummy
          TEST_BBCLOUD_SHA: b511535a89f76d3d311b1c15e3e712b15c0b94e3
